name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        # stop the build if there are python syntax errors or undefined names
        falke8 . --count --select=E9,F63,F7,F82 --show-soure --statistics
        # exit-zero treats all errors as warnings. The Github editor is 127 chars wide
        falke8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Tests
      run: |
        python manage.py test
